# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ubc-fashion-studio-ai-frontend-container

on:
  push:
    branches:
      - feature/main-frontend-deployement
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://gcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7c6ce7c0e927497482ee97329e0fe515 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e92316ef460241bf89fe419394d35fcc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gcr.io/${{ secrets.AzureAppService_ContainerUsername_7c6ce7c0e927497482ee97329e0fe515 }}/kanakamsasikalyan/react-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ubc-fashion-studio-ai-frontend-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fbdda99e588b4c98bc64bf68b97bf2a2 }}
        images: 'gcr.io/${{ secrets.AzureAppService_ContainerUsername_7c6ce7c0e927497482ee97329e0fe515 }}/kanakamsasikalyan/react-frontend:${{ github.sha }}'